export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const DELETE_ITEM = "DELETE_ITEM";
export const ADD_TO_CART = "ADD_TO_CART";
export const SELECT_COMPANY = "SELECT_COMPANY";
